language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies


before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install codecov
    - pip install pycodestyle
    - pip install pydocstyle
    - pip install tox

install:
# command to run tests
  - pip install -r requirements.txt
  
script:
  - coverage run tests.py
#  - pycodestyle --exclude=migrations --max-line-length=120
#  - tox

matrix:
  include:
  - python: 3.6
    env: TOXENV=py36

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always