version: "3.4"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword123
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/mysql/
    networks:
      - aucr

networks:
  aucr:
    driver: bridge