version: "3.4"

services:

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/mysql/
    env_file:
      - ./config-file.env
    networks:
      - aucr

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - aucr
    env_file:
      - ./config-file.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=aucr
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - aucr

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - aucr

networks:
  aucr:
    driver: bridge
