version: "3.4"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
    networks:
      - aucr
    env_file:
      - ./config-file.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=aucr
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - aucr

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=aucradmin
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
    networks:
      - aucr
    env_file:
    - ./config-file.env

  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    volumes:
    - ./mongo-data:/data/db
    networks:
      - aucr

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aucr
      POSTGRES_PASSWORD: postgrespassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - aucr

networks:
  aucr:
    driver: bridge