version: "3.4"

services:

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3307:3306
    env_file:
      - ./config-file.env
    networks:
      - aucr

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - aucr

networks:
  aucr:
    driver: bridge
