version: "3.4"

services:
  aucr:
    image: aucr
    ports:
      - 5000:5000
    networks:
     - aucr

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms16g -Xmx16g"
    networks:
      - aucr

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
      - 5601:5601
    networks:
      - aucr
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - aucr

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword123
    ports:
      - 3307:3306
    volumes:
      - ./mysql/:/mysql/
    networks:
      - aucr

networks:
  aucr:
    driver: bridge



