version: "3.4"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana1
    ports:
      - 5601:5601
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
    networks:
      - aucr
    env_file:
      - ./config-file.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch1
    environment:
      - cluster.name=aucr
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - node.name=es01
      - cluster.initial_master_nodes=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - aucr

  rabbitmq:
    container_name: rabbitmq1
    image: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=twitchstream
      - RABBITMQ_DEFAULT_PASS=passwordtwitchstream
    networks:
      - aucr
    env_file:
    - ./config-file.env

  postgres:
    container_name: postgres1
    image: postgres
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: twitchstream
      POSTGRES_PASSWORD: passwordtwitchstream
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - aucr

networks:
  aucr:
    driver: bridge